macro(ProjectSetupClangDebuggerTuningC)
    if ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
        if ("${CMAKE_C_COMPILER_ID}" STREQUAL "Clang")
            message(STATUS "C: LLVM/clang detected. Enabling LLDB debugger tuning...")
            set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -glldb")
        endif()
    endif()
endmacro()

macro(ProjectSetupClangDebuggerTuningCxx)
    if ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
        if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
            message(STATUS "C++: LLVM/clang detected. Enabling LLDB debugger tuning...")
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -glldb")
        endif()
    endif()
endmacro()
